### ISSUE TITLE
Trying to install on VirtualBox Ubuntu Server 16.04

### ISSUE THREAD

**Issue by saulgudmon** [jplayer/react-jPlayer-examples#3]
just set up a new ubuntu server for testing with VirtualBox. I am planning on building an online radio webpage using react-jplayer. I was able to run the test in Windows by running 'npm install/npm run dev' in cmd
But when I try to run the same procedure in my Ubuntu Server VirtualBox I get errors.
The virtual server is fully updated with apache, proftpd, samba, node.js, and npm installed.

link to "npm-debug.log": https://gist.github.com/PatrickWayland/bd4e7de167b9314583e922644c26f306
screenshot: https://imgur.com/a/CGc33

**Comment by saulgudmon** [comment]
fixed the errors by installing node.js legacy
sudo apt-get install nodejs-legacy
(webpack: Compiled successfully.)

still can't figure out how to access the test page from my host pc. tried the servers local ip address
http://172.16.1.71:8080

and the html file

http://172.16.1.71:8080/react-jPlayer-examples/jPlayers/LivePlayer/public

both return a connection error but when I remove port 8080 from the address the "/LivePlayer/public" URL loads a blank page with the correct title displayed.
The VirtualBox is set up using a bridged ethernet adapter.

**Comment by saulgudmon** [comment]
Using tmux  I was able to "curl localhost:8080" while the webpack continued running in another window I have confirmed that react-jPlayer is running correctly on my server. I am clearly barking up the wrong tree for answers.

**Comment by MartinDawson** [comment]
@PatrickWayland Did you manage to get it working?

**Comment by saulgudmon** [comment]
I didn't. Been trying all night.

**Comment by MartinDawson** [comment]
`http://172.16.1.71:8080` should be the correct format as it should just be the same as running on localhost. I'd try asking on stackoverflow as I have no virtualbox or ubuntu experience.

[Webpack-dev-server](https://webpack.github.io/docs/webpack-dev-server.html) server is on port 8080 by default so that should be correct.
